#!/usr/bin/env python
Import('env')

shaders = [
    '2d',
    '3d',
]

if 'PICA' in env['BUILDERS']:
    for shader in shaders:
        env.PICA(shader)
        env.PICA_HEADER(shader)

source_files = [
    "rasterizer_citro3d.cpp",
    "rasterizer_scene_citro3d.cpp"
]

objects = []

for source_file in source_files:
    objects.append(env.Object(source_file))
objects.append(SConscript("storage/SCsub"))
Return("objects")
