#!/usr/bin/env python
Import('env')

source_files = [
]

objects = []

for source_file in source_files:
    objects.append(env.Object(source_file))
objects.append(SConscript("citro3d/SCsub"))
Return("objects")
