#!/usr/bin/env python

Import("env")

source_files = [
    "mesh_storage.cpp",
    "texture_storage.cpp",
    "utilities.cpp"
]

objects = []

for source_file in source_files:
    objects.append(env.Object(source_file))

Return("objects")